version: '3.8'
services:

  node:
    container_name: medialist-node
    build: node/
    tty: true
    ports:
      - "3002:3000"
    working_dir: /var/www/medialist
    volumes:
      - ./:/var/www/medialist
    networks:
      - medialist-network

  postgres:
    container_name: medialist-postgres
    build: postgres/
    tty: true
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - medialist-network

networks:
  medialist-network:
    driver: bridge
